### ISSUE TITLE
execSync function is failing due to a lack of buffer space

### ISSUE THREAD

**Issue by ramhaidar** [insulineru/ai-commit#12]
When I run 'ai-commit' the following error appears:
![image (11)](https://github.com/insulineru/ai-commit/assets/49301219/07615aa8-d60b-485b-84d1-5289dee7ab62)
```
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync C:\WINDOWS\system32\cmd.exe ENOBUFS
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:871:24)
    at execSync (node:child_process:952:15)
    at generateAICommit (file:///D:/Program%20Files/node.js/node_modules/ai-commit/index.js:114:16)
    at file:///D:/Program%20Files/node.js/node_modules/ai-commit/index.js:131:7
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  errno: -4060,
  code: 'ENOBUFS',
  syscall: 'spawnSync C:\\WINDOWS\\system32\\cmd.exe',
  path: 'C:\\WINDOWS\\system32\\cmd.exe',
  spawnargs: [ '/d', '/s', '/c', '"git diff --staged"' ],
  error: [Circular *1],
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    Buffer(1064960) [Uint8Array] [
      100, 105, 102, 102,  32,  45,  45, 103, 105, 116,  32,  97,
       47,  97, 112, 112,  47,  72, 116, 116, 112,  47,  67, 111,
      110, 116, 114, 111, 108, 108, 101, 114, 115,  47,  68,  97,
      115, 104,  98, 111,  97, 114, 100,  67, 111, 110, 116, 114,
      111, 108, 108, 101, 114,  46, 112, 104, 112,  32,  98,  47,
       97, 112, 112,  47,  72, 116, 116, 112,  47,  67, 111, 110,
      116, 114, 111, 108, 108, 101, 114, 115,  47,  68,  97, 115,
      104,  98, 111,  97, 114, 100,  67, 111, 110, 116, 114, 111,
      108, 108, 101, 114,
      ... 1064860 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 16112,
  stdout: Buffer(1064960) [Uint8Array] [
    100, 105, 102, 102,  32,  45,  45, 103, 105, 116,  32,  97,
     47,  97, 112, 112,  47,  72, 116, 116, 112,  47,  67, 111,
    110, 116, 114, 111, 108, 108, 101, 114, 115,  47,  68,  97,
    115, 104,  98, 111,  97, 114, 100,  67, 111, 110, 116, 114,
    111, 108, 108, 101, 114,  46, 112, 104, 112,  32,  98,  47,
     97, 112, 112,  47,  72, 116, 116, 112,  47,  67, 111, 110,
    116, 114, 111, 108, 108, 101, 114, 115,  47,  68,  97, 115,
    104,  98, 111,  97, 114, 100,  67, 111, 110, 116, 114, 111,
    108, 108, 101, 114,
    ... 1064860 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}

Node.js v18.16.0
```

**Comment by ramhaidar** [comment]
Modified the code and it worked! (Changed the code to use "spawnSync" instead of "execSync")
```
#!/usr/bin/env node

'use strict'
import { spawnSync } from "child_process";
import { ChatGPTAPI } from "chatgpt";
import inquirer from "inquirer";
import { getArgs, checkGitRepository } from "./helpers.js";
import { addGitmojiToCommitMessage } from './gitmoji.js';
import { filterApi } from "./filterApi.js";

import * as dotenv from 'dotenv';
dotenv.config();

const args = getArgs();

const REGENERATE_MSG = "♻️ Regenerate Commit Messages";

const apiKey = args.apiKey || process.env.OPENAI_API_KEY;
if (!apiKey) {
  console.error("Please set the OPENAI_API_KEY environment variable.");
  process.exit(1);
}

const api = new ChatGPTAPI({
  apiKey,
});

const makeCommit = (input) => {
  console.log("Committing Message... 🚀 ");
  spawnSync('cmd', ['/c', 'git commit -F -'], { input, maxBuffer: 1024 * 1024 * 10 });
  console.log("Commit Successful! 🎉");
};

const generateSingleCommit = async (diff) => {
  const prompt =
    "I want you to act as the author of a commit message in git."
    + "I'll enter a git diff, and your job is to convert it into a useful commit message."
    + "Do not preface the commit with anything, use the present tense, return the full sentence, and use the conventional commits specification (<type in lowercase>: <subject>):"
    + diff;

  if (!await filterApi({ prompt, filterFee: args['filter-fee'] })) process.exit(1);

  const { text } = await api.sendMessage(prompt);

  const gitmojiCommit = addGitmojiToCommitMessage(text);

  console.log(
    `Proposed Commit:\n------------------------------\n${gitmojiCommit}\n------------------------------`
  );

  if (args.force) {
    makeCommit(gitmojiCommit);
    return;
  }

  const answer = await inquirer.prompt([
    {
      type: "confirm",
      name: "continue",
      message: "Do you want to continue?",
      default: true,
    },
  ]);

  if (!answer.continue) {
    console.log("Commit aborted by user 🙅‍♂️");
    process.exit(1);
  }

  makeCommit(gitmojiCommit);
};

const generateListCommits = async (diff, numOptions = 5) => {
  const prompt =
    "I want you to act as the author of a commit message in git."
    + `I'll enter a git diff, and your job is to convert it into a useful commit message and make ${numOptions} options that are separated by ";".`
    + "For each option, use the present tense, return the full sentence, and use the conventional commits specification (<type in lowercase>: <subject>):"
    + diff;

  if (!await filterApi({ prompt, filterFee: args['filter-fee'], numCompletion: numOptions })) process.exit(1);

  const { text } = await api.sendMessage(prompt);

  const msgs = text.split(";").map((msg) => msg.trim()).map(msg => addGitmojiToCommitMessage(msg));

  // add regenerate option
  msgs.push(REGENERATE_MSG);

  const answer = await inquirer.prompt([
    {
      type: "list",
      name: "commit",
      message: "Select a commit message",
      choices: msgs,
    },
  ]);

  if (answer.commit === REGENERATE_MSG) {
    await generateListCommits(diff);
    return;
  }

  makeCommit(answer.commit);
};

async function generateAICommit() {
  const isGitRepository = checkGitRepository();

  if (!isGitRepository) {
    console.error("This is not a git repository 🙅‍♂️");
    process.exit(1);
  }

  const result = spawnSync('cmd', ['/c', 'git diff --staged'], { maxBuffer: 1024 * 1024 *10 });
  
   // Handle empty diff
   if (!result.stdout.toString()) {
     console.log("No changes to commit 🙅");
     console.log(
       "May be you forgot to add the files? Try git add . and then run this script again."
     );
     process.exit(1);
   }
 
   args.list
     ? await generateListCommits(result.stdout.toString())
     : await generateSingleCommit(result.stdout.toString());
}

await generateAICommit();

```
