### ISSUE TITLE
Script crashes with fetch not defined

### ISSUE THREAD

**Issue by Galionix** [insulineru/ai-commit#2]
Please explain why its happening

`PS F:\work\lp-backInbox> ai-commit 
file:///C:/Users/Dimas/AppData/Roaming/npm/node_modules/ai-commit/node_modules/chatgpt/build/index.js:139
      throw new Error("Invalid environment; fetch is not defined");
            ^

Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///C:/Users/Dimas/AppData/Roaming/npm/node_modules/ai-commit/node_modules/chatgpt/build/index.js:139:13)
    at file:///C:/Users/Dimas/AppData/Roaming/npm/node_modules/ai-commit/index.js:20:13
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)`

**Comment by Galionix** [comment]
Not reproduced on node v18.12.1

**Comment by insulineru** [comment]
Hello, @Galionix. I completely forgot to add in the README that the minimum Node.JS version to run is 16, I will add that in the next update. Thanks for the reminder :)

**Comment by endAurum** [comment]
Still an issue for Node 16.18.0

**Comment by insulineru** [comment]
@endAurum check the `npx` settings and make sure the script is called from node 16. You can also attach a .log file of the error, I'll take a look at it.

**Comment by SQReder** [comment]
```
λ ai-commit                                                                                                          
file:///C:/Users/___/AppData/Roaming/npm/node_modules/ai-commit/node_modules/chatgpt/build/index.js:150
      throw new Error("Invalid environment; fetch is not defined");                                           
            ^                                                                                                 

Error: Invalid environment; fetch is not defined
    at new ChatGPTAPI (file:///C:/Users/___/AppData/Roaming/npm/node_modules/ai-commit/node_modules/chatgpt/build/index.js:150:13)
    at file:///C:/Users/___/AppData/Roaming/npm/node_modules/ai-commit/index.js:24:13
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

λ node -v
v16.18.0

λ npx -v
8.19.3
```

**Comment by squillace91** [comment]
same issue here

**Comment by danivalls** [comment]
Same issue here.
`node: v16.19.0`
`npx: 8.19.3`
